### ISSUE TITLE
Admin Taxonomies Page Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by cloudrck** [spree/spree#5948]
After I upgraded from Spree 2.2 to 2.3, I found that the page to edit taxonomies in the admin area was no longer working. None of the child taxons are loaded, and it is impossible to manipulate or edit them.

The following error shows up in Chrome
```Uncaught TypeError: undefined is not a function all-99c43dd7160e27fd161fc5757ec34be5.js:17```

My Gemfiles https://gist.github.com/cloudrck/176dd4b118d8868abe54

Line 17
https://gist.github.com/cloudrck/12ea90e82b5f6d4d417c

**Comment by JDutil** [comment]
close:works_for_me

**Comment by spreebot** [comment]
We could not reproduce this issue on a clean install.

Don't get discouraged that your issue has been closed, Spree is a busy project and gets a lot of issues. Please reopen this issue with more information on how to reproduce this.
