### ISSUE TITLE
undefined method `amount' for Spree::ReturnAuthorization

### ISSUE THREAD

**Issue by Waylon87** [spree/spree#5892]
#### Spree 2.3.7 beta

I'm trying to process a return authorization.

Steps.
1. go to processed order
2. click on return authorizations
3. click new return authorization
4. error when rendering return_authorizations/_form

 I'm getting the following error.

```undefined method `amount' for #<Spree::ReturnAuthorization:0x007fed750008b0>```

``` 
     <% if @return_authorization.received? %>
         <%= @return_authorization.display_amount %>
     <% else %>
       <%= f.text_field :amount, {:style => 'width:80px;'} %> <%= Spree.t(:rma_value) %>: <span id="rma_value">0.00</span>
       <%= f.error_message_on :amount %>
    <% end %>
```

Full Stack Trace

```
activemodel (4.1.8) lib/active_model/attribute_methods.rb:435:in `method_missing'
activerecord (4.1.8) lib/active_record/attribute_methods.rb:213:in `method_missing'
actionview (4.1.8) lib/action_view/helpers/tags/base.rb:28:in `public_send'
actionview (4.1.8) lib/action_view/helpers/tags/base.rb:28:in `value'
actionview (4.1.8) lib/action_view/helpers/tags/base.rb:37:in `value_before_type_cast'
actionview (4.1.8) lib/action_view/helpers/tags/text_field.rb:9:in `block in render'
actionview (4.1.8) lib/action_view/helpers/tags/text_field.rb:9:in `fetch'
actionview (4.1.8) lib/action_view/helpers/tags/text_field.rb:9:in `render'
actionview (4.1.8) lib/action_view/helpers/form_helper.rb:771:in `text_field'
actionview (4.1.8) lib/action_view/helpers/form_helper.rb:1258:in `text_field'
app/views/spree/admin/return_authorizations/_form.html.erb:40:in `block in _64929ca730ea7e92436dc3adc3c4825f'
actionview (4.1.8) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
actionview (4.1.8) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
actionview (4.1.8) lib/action_view/helpers/capture_helper.rb:38:in `capture'
/Users/xxx/.rvm/gems/ruby-2.0.0-p247/bundler/gems/spree-c2fd238033d6/backend/app/helpers/spree/admin/base_helper.rb:10:in `field_container'
/Users/xxx/.rvm/gems/ruby-2.0.0-p247/bundler/gems/spree-c2fd238033d6/backend/config/initializers/form_builder.rb:6:in `field_container'
app/views/spree/admin/return_authorizations/_form.html.erb:35:in `_64929ca730ea7e92436dc3adc3c4825f'
actionview (4.1.8) lib/action_view/template.rb:145:in `block in render'
activesupport (4.1.8) lib/active_support/notifications.rb:161:in `instrument'
actionview (4.1.8) lib/action_view/template.rb:339:in `instrument'
actionview (4.1.8) lib/action_view/template.rb:143:in `render'
deface (1.0.1) lib/deface/action_view_extensions.rb:41:in `render'
actionview (4.1.8) lib/action_view/renderer/partial_renderer.rb:306:in `render_partial'
actionview (4.1.8) lib/action_view/renderer/partial_renderer.rb:279:in `block in render'
actionview (4.1.8) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (4.1.8) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.1.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.1.8) lib/active_support/notifications.rb:159:in `instrument'
actionview (4.1.8) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionview (4.1.8) lib/action_view/renderer/partial_renderer.rb:278:in `render'
actionview (4.1.8) lib/action_view/renderer/renderer.rb:47:in `render_partial'
actionview (4.1.8) lib/action_view/renderer/renderer.rb:21:in `render'
actionview (4.1.8) lib/action_view/helpers/rendering_helper.rb:32:in `render'
/Users/xxx/.rvm/gems/ruby-2.0.0-p247/bundler/gems/spree-c2fd238033d6/backend/app/views/spree/admin/return_authorizations/new.html.erb:14:in `block in _fd2bcaf27615a68da0005ea58649b6c6'
actionview (4.1.8) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
actionview (4.1.8) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
actionview (4.1.8) lib/action_view/helpers/capture_helper.rb:38:in `capture'
actionview (4.1.8) lib/action_view/helpers/form_helper.rb:434:in `form_for'
/Users/xxx/.rvm/gems/ruby-2.0.0-p247/bundler/gems/spree-c2fd238033d6/backend/app/views/spree/admin/return_authorizations/new.html.erb:12:in `_fd2bcaf27615a68da0005ea58649b6c6'
actionview (4.1.8) lib/action_view/template.rb:145:in `block in render'
activesupport (4.1.8) lib/active_support/notifications.rb:161:in `instrument'
actionview (4.1.8) lib/action_view/template.rb:339:in `instrument'
actionview (4.1.8) lib/action_view/template.rb:143:in `render'
deface (1.0.1) lib/deface/action_view_extensions.rb:41:in `render'
actionview (4.1.8) lib/action_view/renderer/template_renderer.rb:55:in `block (2 levels) in render_template'
actionview (4.1.8) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (4.1.8) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.1.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.1.8) lib/active_support/notifications.rb:159:in `instrument'
actionview (4.1.8) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionview (4.1.8) lib/action_view/renderer/template_renderer.rb:54:in `block in render_template'
actionview (4.1.8) lib/action_view/renderer/template_renderer.rb:62:in `render_with_layout'
actionview (4.1.8) lib/action_view/renderer/template_renderer.rb:53:in `render_template'
actionview (4.1.8) lib/action_view/renderer/template_renderer.rb:17:in `render'
actionview (4.1.8) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (4.1.8) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (4.1.8) lib/action_view/rendering.rb:99:in `_render_template'
actionpack (4.1.8) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (4.1.8) lib/action_view/rendering.rb:82:in `render_to_body'
actionpack (4.1.8) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
actionpack (4.1.8) lib/action_controller/metal/renderers.rb:32:in `render_to_body'
actionpack (4.1.8) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (4.1.8) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
activesupport (4.1.8) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/xxx/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
activesupport (4.1.8) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:41:in `block in render'
actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
activerecord (4.1.8) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:40:in `render'
/Users/xxx/.rvm/gems/ruby-2.0.0-p247/bundler/gems/spree-c2fd238033d6/backend/app/controllers/spree/admin/resource_controller.rb:13:in `block (2 levels) in new'
/Users/xxx/.rvm/gems/ruby-2.0.0-p247/bundler/gems/spree-c2fd238033d6/core/lib/spree/core/controller_helpers/respond_with.rb:16:in `call'
/Users/xxx/.rvm/gems/ruby-2.0.0-p247/bundler/gems/spree-c2fd238033d6/core/lib/spree/core/controller_helpers/respond_with.rb:16:in `respond_with'
/Users/xxx/.rvm/gems/ruby-2.0.0-p247/bundler/gems/spree-c2fd238033d6/backend/app/controllers/spree/admin/resource_controller.rb:12:in `new'
actionpack (4.1.8) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.1.8) lib/abstract_controller/base.rb:189:in `process_action'
actionpack (4.1.8) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.1.8) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.1.8) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:149:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:149:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:149:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:229:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:229:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:229:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:229:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:86:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:86:in `run_callbacks'
actionpack (4.1.8) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.1.8) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.1.8) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.1.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.1.8) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.1.8) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.1.8) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.1.8) lib/abstract_controller/base.rb:136:in `process'
actionview (4.1.8) lib/action_view/rendering.rb:30:in `process'
actionpack (4.1.8) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.1.8) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.1.8) lib/action_controller/metal.rb:232:in `block in action'
actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:82:in `call'
actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:50:in `call'
actionpack (4.1.8) lib/action_dispatch/journey/router.rb:73:in `block in call'
actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:678:in `call'
railties (4.1.8) lib/rails/engine.rb:514:in `call'
railties (4.1.8) lib/rails/railtie.rb:194:in `public_send'
railties (4.1.8) lib/rails/railtie.rb:194:in `method_missing'
actionpack (4.1.8) lib/action_dispatch/journey/router.rb:73:in `block in call'
actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:678:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
rack (1.5.2) lib/rack/etag.rb:23:in `call'
rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
rack (1.5.2) lib/rack/head.rb:11:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/flash.rb:254:in `call'
rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.1.8) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.1.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
activerecord (4.1.8) lib/active_record/migration.rb:380:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.1.8) lib/active_support/callbacks.rb:82:in `run_callbacks'
actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.1.8) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.1.8) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.1.8) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.1.8) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
rack (1.5.2) lib/rack/runtime.rb:17:in `call'
activesupport (4.1.8) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/static.rb:84:in `call'
rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
railties (4.1.8) lib/rails/engine.rb:514:in `call'
railties (4.1.8) lib/rails/application.rb:144:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
rack (1.5.2) lib/rack/content_length.rb:14:in `call'
rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
/Users/xxx/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
/Users/xxx/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
/Users/xxx/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
```
If I comment out line 40 to see what happens
```
<%= f.text_field :amount, {:style => 'width:80px;'} %> <%= Spree.t(:rma_value) %>: <span id="rma_value">0.00</span>
```
Then I just get an undefined method 'reason' which is the next field in the form. 

I've looked around to see what could be causing this and can't seem to come to a conclusion. 

The issue is occuring on development and production.

Any help as into what I can do to fix this would be greatly appreciated.

**Comment by JDutil** [comment]
I'm not sure why you'd be having that error.  It sounds like your missing migrations for the return authorization.  Make sure those fields exist on the return authorizations table in your database.

close:works_for_me

**Comment by spreebot** [comment]
We could not reproduce this issue on a clean install.

Don't get discouraged that your issue has been closed, Spree is a busy project and gets a lot of issues. Please reopen this issue with more information on how to reproduce this.

**Comment by Waylon87** [comment]
It looks like somehow I'm in between versions on this. From what I can tell Spree 2.3 uses the version with "amount" and "reason", yet 2.4 drops these in favor for "memo" and "amount fields" on the `spree_return_items` table.

So my views and controllers are at 2.3 but somehow the migrations for the updated version (2.4) got in this version?

My migrations and tables have dropped the "amount" column and renamed the "reason" column to "memo" which is what shows up in the spree user guide and what looks like works with Spree 2.4 

Here is my return_authorizations table

```
                                               Table "public.spree_return_authorizations"
             Column             |            Type             |                                Modifiers                                 
--------------------------------+-----------------------------+--------------------------------------------------------------------------
 id                             | integer                     | not null default nextval('spree_return_authorizations_id_seq'::regclass)
 number                         | character varying(255)      | 
 state                          | character varying(255)      | 
 order_id                       | integer                     | 
 memo                           | text                        | 
 created_at                     | timestamp without time zone | 
 updated_at                     | timestamp without time zone | 
 stock_location_id              | integer                     | 
 return_authorization_reason_id | integer                     | 
Indexes:
    "spree_return_authorizations_pkey" PRIMARY KEY, btree (id)
    "index_return_authorizations_on_return_authorization_reason_id" btree (return_authorization_reason_id)
```

I also show a migration for "Spree::LegacyReturnAuthorization" which I definitely thought was version 2.4. Which was, from what I read, supposed to be for upgrading from 2.3 to 2.4.. I'm on 2.3.7 beta, so I'm not sure why these would be included. 

This doesn't seem right to me... 

Let me know if this is making sense.

**Comment by Waylon87** [comment]
Yes. I can confirm. Somehow I have the migrations from 2.4 but all other code from 2.3. I installed 2.3 from the start so I am baffled at how the 2.4 migrations could have been copied over. I'm not sure of a way to replace the 2.4 migrations with 2.3 migrations besides manually copying all of them and dropping the Db all together and recreating it. But then I wonder if it would be easier to just upgrade to 2.4 and patch/update all my installed extensions to 2.4.

**Comment by JDutil** [comment]
That's strange perhaps you used the spree command with a newer gem installed on your system instead of the version in your Gemfile or something along those lines.
