### ISSUE TITLE
NameError: undefined local variable or method `try_spree_current_user'

### ISSUE THREAD

**Issue by mrbrdo** [spree/spree#11997]
Hello, after update from 4.5 to 4.7 I started seeing this error on otherwise invalid requests (from crawlers), but anyway:
```
NameError: undefined local variable or method `try_spree_current_user' for #<Spree::Api::V1::UsersController:0x000000031b4510>

          Spree::Config.use_user_locale && try_spree_current_user && supported_locale?(try_spree_current_user.selected_locale)
```
I guess the try_spree_current_user was added to Spree, but it wasn't added to [spree_api_v1](https://github.com/spree/spree_api_v1), hence this error on api v1 endpoints.

Example of path (when spree_api_v1 gem is installed): `/api/v1/users`

Should be a really easy fix, but I'm not sure which way you want to go with it so I rather opened an issue instead of a PR.

ref:
https://github.com/spree/spree/pull/11820
@wjwitek 

Cheers

**Comment by mrbrdo** [comment]
@wjwitek

**Comment by wjwitek** [comment]
Hi, if you would like to make a PR, I think adding alias 'try_spree_current_user' to a method that fetches a user in spree_api_v1 would make sense.
That being said, spree_api_v1 is deprecated and it's possible it won't be compatible with future spree versions.

**Comment by mrbrdo** [comment]
@wjwitek thanks for the answer. After looking at this more, I am not sure if spree_rails_frontend is even using api v1 anymore. Do you know? I think in the past it did use it, but after checking with v4.7, I can't find if it's still used.

**Comment by wjwitek** [comment]
@mrbrdo, I'm not sure, but spree_api_v1 is not a dependency of spree_rails_frontend so I guess it doesn't use it.

**Comment by mrbrdo** [comment]
Ok thanks. I guess this is an issue of spree_api_v1 then.
