### ISSUE TITLE
undefined method `available_on' for class Spree::Product

### ISSUE THREAD

**Issue by shahroz-17** [spree/spree#12277]
I have updated spree gem from 4.6 to 4.10 and when i am trying to create product it's giving undefined error for available_on.

`product = store.products.new(client_id: client_id, name: "p", shipping_category_id: category_id, taxon_ids: [taxon_id], selected_taxon_ids: [taxon_id], option_type_ids: [option_type.id], store_ids: [store.id], product_type: "gift", digital_service_provider: "tsgifts", delivery_mode: "tsgift_digital", ts_type: "monetary", send_gift_card_via: "email", voucher_email_image: "product_image", vendor_id: vendor_id, price: "0", available_on: DateTime.now, minimum_order_quantity: 1, default_quantity: 1)

product.save!`

@damianlegawiec

**Comment by damianlegawiec** [comment]
Hey @shahroz-17 `available_on` is a standard database column in the `spree_products` table. Please check your `db/schema.sql` file. We didn't remove it, but maybe someone on your team accidentally did it with a DB migration.

**Comment by shahroz-17** [comment]
Hey @damianlegawiec Thanks for responding, available_on is defined in my schema.rb, If i try to get available_on of any product in rails console than it returns its value but when i am trying to create a product with Spree::Product.create it gives **undefined method `available_on' for class Spree::Product.** 
It was working fine in spree 4.6 but after upgrading to 4.10 it's giving error while creating product.
I don't know if the issue is arising because of some bug in spree 4.10 or some gem dependency is causing this issue.

**I shall be very thankful if you help me out with this issue**
